### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by wwalc** [WebSpellChecker/ckeditor-plugin-scayt#115]
Just to keep things clean: 

1. CKSource / external_plugin can be dropped I guess?
2. changes form scayt-dev can be merged into master since it's going to be included in 4.5.6?

**Comment by KremYura** [comment]
Thanks for your attention on that. We are in progress with WebSpellChecker.net 4.8.2 release and plan to merge `scayt-dev` into `master` within 1 week (due to our current release procedure).

Also, we plan to perform full cleanup on our repo and update development procedure of SCAYT plugin according to comments from @Reinmar, after 4.8.2 release.

**Comment by WebSpellChecker** [comment]
Merged, thank you again.
