### ISSUE TITLE
Soft hyphens cause problems 

### ISSUE THREAD

**Issue by danielwirz** [WebSpellChecker/ckeditor-plugin-scayt#177]
Hi there

Words that contain soft hyphens (&amp;shy;) cannot be spell-checked. Instead, a soft hyphen splits a word into 2 words that are spell-checked separately.

![image](https://user-images.githubusercontent.com/42937331/97884212-18627300-1d26-11eb-9b96-16e658930f36.png)

Best regards
daniel

**Comment by jshaptala** [comment]
Hi @danielwirz,

Thanks for drawing our attention to this behavior.

Would you please clarify a few things:

1. What language do you use for spell-checking?
2. Is your expectation to have the whole word spell-checked? Or should it be ignored at all if it has `&shy;` symbol?
3. Do you insert `&shy;` manually? Or is it inserted automatically within an editor?

Right now `&shy;` is a separator for our spelling engine. Thus, the word is checked separately.

Thanks,

**Comment by danielwirz** [comment]
hi @jshaptala,

Sorry for being a bit unspecific. Here's the information:
1. I checked it in German and English
2. Yes, I expected to have the whole word spell-checked.
3. Yes, I added the `&shy;` manually.

I think, the `&shy;` should be ignored by the spell-checker since it's not affecting the word itself – it only affects the visual representation.

Thanks a lot

**Comment by jshaptala** [comment]
Hi @danielwirz,

Thanks a lot for the additional information. It was very useful.

In general, I do support your point of view here. We can remove `&shy;` from a list of separators and check the whole word, ignoring the soft hyphen. 

However, if there is a mistake in the word, the generated suggestion by the engine won't contain `&shy;` symbol. So if a user replaces a word with a given suggestion from the list, `&shy;` will be removed. I believe that this is not expected behavior too.

We are discussing internally what other options are...

**Comment by danielwirz** [comment]
Hi @jshaptala 

Thanks a lot for your feedback, that sounds perfect for me. 

When I think this through, I would not expect the engine to provide `&shy;` symobls in the suggestions. Currently, we have to manually add the symbol. Therefore, it makes sense to me that we need to re-add it once the word was replaced by a suggestion from the engine.

Thanks a lot!

**Comment by jshaptala** [comment]
Hi @danielwirz,

Thanks for sharing your thoughts and confirming your expectations about how the fix should work. 

This is exactly what we can do. By the way, we decided to include this fix in our upcoming release that is planned for tomorrow. So, the mentioned problem should be fixed with this release. No updates on the plugin or from your side is not required as this is the fix on the back-end component.

Cheers,

**Comment by danielwirz** [comment]
hi @jshaptala 

Perfect, that's great news! 
Thanks a lot, we're really looking forward to this!

cheers & have good day!

**Comment by danielwirz** [comment]
Hi @jshaptala 

I just tested the spell checker and the issue seems to be solved.
As far as I can tell, the spell checking works now the way I'd expect it.

Thanks a lot for the great support and the fast trouble shooting!
Cheers & have good day!

**Comment by jshaptala** [comment]
Hi @danielwirz,

Our team finalized the release this morning and the fix is there. Thanks for being proactive and confirming that it works for you as well. 

We are doing our best to provide the best service we can.

Cheers!

**Comment by jshaptala** [comment]
Hi @danielwirz,

Thanks for your patience. Finally, we were able to roll out the updated version of the package which includes the fix. 

Regards,

**Comment by danielwirz** [comment]
Hi @jshaptala 

We just checked and it seems to work perfectly!
Thanks a lot, we're really happy!

Cheers

**Comment by jshaptala** [comment]
Hi @danielwirz, we are pleased to hear that it works good and you are happy with the result.
