### ISSUE TITLE
SCAYT CORE: IE 8, 9: Focus is not restored inside a misspelled word for paste action from toolbar

### ISSUE THREAD

**Issue by WebSpellChecker** [WebSpellChecker/ckeditor-plugin-scayt#93]
Steps:
1. Open sample page with SCAYT + CKEditor 4 with Inline mode
2. Put the cursor inside a misspelled word
3. Try to paste a word with CK's toolbar and Allow Access window

Expected result: the word is pasted to the initial focus
Actual result: the word is pasted at the beginning of the misspelled word

**Comment by wsc-bug-hunter** [comment]
Hello ghost,

I hope you are doing great!

Sorry for such a huge delay in response. I have tried to reproduce this issue on IE9 and IE8 with the latest CKEditor version and latest version of our product. Looks like this issue is deprecated and paste works as expected.

Could you please tell me if this issue is still actual for you?

Regards,
WebSpellChecker

**Comment by wsc-julia-shaptala** [comment]
Hello, This issue has been fixed a while ago and this is not reproducible on the last versions of the SCAYT plugin (4.8.9-4.9.2.1).
