### ISSUE TITLE
Change spell checking language by code

### ISSUE THREAD

**Issue by luisfontes19** [WebSpellChecker/ckeditor-plugin-scayt#94]
This is not an issue, but can someone tell me how can I change the spellchecking language by javascript code, instead of the config.js file?

**Comment by WebSpellChecker** [comment]
Do you want to change spell check language dynamically on created instance of CK with SCAYT or you are looking into another ways to configure initial spellcheck language except config.js ?

**Comment by luisfontes19** [comment]
I need to change it on a created instance...

**Comment by WebSpellChecker** [comment]
In order to change spell check language you need to use following method:
CKEDITOR.instances.your_editor_name.scayt.commitOption({changedOptions: {lang: 'language_code'}})

Please note that this method is not safe, you will need to check by yourself whether new spellcheck language is supported by SCAYT or no. Here is the default list of supported languages:
"en_US", "en_GB", "fr_FR", "de_DE", "it_IT", "es_ES", "pt_BR", "da_DK", "nl_NL", "nb_NO", "pt_PT", "sv_SE", "el_GR", "en_CA", "fr_CA", "fi_FI"

Also appropriate changes will take place only if you will apply spell check language different from current one.

**Comment by luisfontes19** [comment]
I'm having the following error:

TypeError: undefined is not an object (evaluating 'CKEDITOR.instances.issue_description.scayt.commitOption')

CKEDITOR.instances.issue_description.scayt returns nothing, but scayt is enabled... and I can access some options through CKEDITOR.instances.issue_description.plugins.scayt, but it has nothing related to commigOption...

**Comment by WebSpellChecker** [comment]
What is the version of SCAYT that you use? You can check it from 'About' tab in SCAYT dialog window. It seems like your scayt plugin is outdated

**Comment by luisfontes19** [comment]
Wow, 2.8, really old indeed, I'll update then, thank you for your time
