### ISSUE TITLE
Options scayt_minWordLength is not available in build package

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/ckeditor-plugin-scayt#96]
Please see: http://dev.ckeditor.com/ticket/13272

This variable is available in github for SCAYT - https://github.com/WebSpellChecker/ckeditor-plugin-scayt/blob/6b3f5a880a4ad8152044cf336beb1624c4ca7d7d/plugin.js#L491 but it is not available in CKEditor add-ons package http://ckeditor.com/addon/scayt.

If you download the package, you will not find scayt_minWordLength in source code. Could you perhaps tell us what is the reason of such state? Is it a bug or it supposed to work that way?

**Comment by WebSpellChecker** [comment]
The feature is available in the master branch. It is not included into the CKEditor v4.4.7 package because the release was later. It'll be available in the upcoming CKEditor's release. And it is already available in CKEditor 4.5 beta version. Please find the change log of the WebSpellChecker.net release 4.6:  http://wiki.webspellchecker.net/doku.php?id=changelogs:hosted
